name: Publish to github registry

on: workflow_dispatch

jobs:
  publish-to-github-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
          scope: "@cianciarusocataldo"
          always-auth: "true"
      - run: |
          npm ci
          npx --yes json -I -f package.json -e "this.name=\"@cianciarusocataldo/mobrix-ui\""
          npx --yes json -I -f package.json -e "this.publishConfig={\"registry\": \"https://npm.pkg.github.com\"}"
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare release notes
        run: |
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
