name: Publish MoBrix-ui package to github registry

on: workflow_dispatch

jobs:
  publish-package-to-github-registry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build
      - run: |
          npm run update:package-json "this.name=\"@cianciarusocataldo/mobrix-ui\""
          npm run update:package-json "this.publishConfig={\"registry\": \"https://npm.pkg.github.com\"}"
          touch .npmrc
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_ACCESS_TOKEN }} >>.npmrc
          npm publish --access public
